![Self Check Exercises check mark image](files/art/check.png)
# 7.8 Self Check

**2. _(IPython Session)_** Use NumPy random-number generation to create an array of twelve random grades in the range 60 through 100, then reshape the result into a 3-by-4 array. Calculate the average of all the grades, the averages of the grades in each column and the averages of the grades in each row. 

**Answer:** 

In [2]:
import numpy as np

In [4]:
grades = np.random.randint(60, 101, 12).reshape(3, 4)

In [5]:
grades

array([[74, 67, 70, 96],
       [89, 89, 62, 86],
       [95, 74, 86, 71]])

In [6]:
grades.mean()

79.91666666666667

In [7]:
grades.mean(axis=0)

array([86.        , 76.66666667, 72.66666667, 84.33333333])

In [8]:
grades.mean(axis=1)

array([76.75, 81.5 , 81.5 ])

In [ ]:
##########################################################################
# (C) Copyright 2019 by Deitel & Associates, Inc. and                    #
# Pearson Education, Inc. All Rights Reserved.                           #
#                                                                        #
# DISCLAIMER: The authors and publisher of this book have used their     #
# best efforts in preparing the book. These efforts include the          #
# development, research, and testing of the theories and programs        #
# to determine their effectiveness. The authors and publisher make       #
# no warranty of any kind, expressed or implied, with regard to these    #
# programs or to the documentation contained in these books. The authors #
# and publisher shall not be liable in any event for incidental or       #
# consequential damages in connection with, or arising out of, the       #
# furnishing, performance, or use of these programs.                     #
##########################################################################
