In [1]:
jj = []

In [3]:
jj.append(1)

In [7]:
jj.append('nice hat')

In [8]:
jj

[1, 'nice hat']

In [9]:
jj = [1, 'nice hat']

In [10]:
jj

[1, 'nice hat']

In [11]:
jj ={}

In [12]:
jj['dog']='dalmatian'

In [13]:
jj[1]=42

In [14]:
jj

{'dog': 'dalmatian', 1: 42}

In [31]:
jj = {'dog': 'dalmatian', 1:42}

In [16]:
jj

{'dog': 'dalmatian', 1: 42}

In [17]:
a = [1,2,2,2,4,5,5]

In [18]:
sA=set(a)

In [19]:
sA

{1, 2, 4, 5}

In [20]:
sB=set([4,5,6,7])

In [22]:
sA-sB

{1, 2}

In [23]:
sA | sB

{1, 2, 4, 5, 6, 7}

In [24]:
sA & sB

{4, 5}

In [27]:
if jj < 3:
    print("its's less than three man")

TypeError: '<' not supported between instances of 'dict' and 'int'

In [30]:
sB
for item in sB:
    print(item)

4
5
6
7


In [32]:
for item in jj:
    print(item, jj[item])

dog dalmatian
1 42


In [33]:
a=[1,2,2,2,4,5,5]

In [34]:
myList = [item*4 for item in a]

In [35]:
myList=[]

In [37]:
for item in a:
    myList.append(item*4)

In [38]:
myList

[4, 8, 8, 8, 16, 20, 20]

In [40]:
a="Ophthamology"

In [41]:
my = []

In [51]:
count=0

In [52]:
my= [count+1 for item in a]

In [56]:
import pandas as pd

In [58]:
my.count

<function list.count>

In [63]:
[item*4 for item in a if item>2]

TypeError: '>' not supported between instances of 'str' and 'int'

In [65]:
from numpy import array

In [66]:
mm=array([1,1,1])

In [67]:
pp=array([1,2,3])

In [68]:
pp+mm

array([2, 3, 4])

In [69]:
pp*2

array([2, 4, 6])

In [70]:
pp**2

array([1, 4, 9], dtype=int32)

In [71]:
pp[1]

2

In [72]:
pp

array([1, 2, 3])

In [74]:
jj=array([[1,2,3], [1,1,1]])

In [75]:
jj[0]

array([1, 2, 3])

In [76]:
jj[0][1]

2

In [77]:
jj[0,1]

2

In [78]:
a1=array([1,2,3])

In [80]:
a2=array([0.3,0.2,0.3])

In [81]:
a1+a2

array([1.3, 2.2, 3.3])

In [82]:
from numpy import mat, matrix

In [83]:
ss=mat([1,2,3])

In [84]:
ss

matrix([[1, 2, 3]])

In [85]:
pyList=[5,11,1605]

In [86]:
mat(pyList)

matrix([[   5,   11, 1605]])

In [87]:
mm=matrix([1,2,3])

In [88]:
mm*ss.T

matrix([[14]])

In [89]:
import numpy as np

In [90]:
np.shape(mm)

(1, 3)

In [91]:
mm.shape

(1, 3)

In [92]:
multiply(mm, ss)

NameError: name 'multiply' is not defined

In [93]:
from numpy import multiply

In [94]:
multiply(mm, ss)

matrix([[1, 4, 9]])